<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-03T17:30:22 IST" name="Suite" finished-at="2024-06-03T17:32:53 IST" duration-ms="150701">
    <groups>
      <group name="Error">
        <method signature="SubmitOrder.ErrorValidation()[pri:2, instance:SeleniumProj.AutomateFramework2.SubmitOrder@545b995e]" name="ErrorValidation" class="SeleniumProj.AutomateFramework2.SubmitOrder"/>
      </group> <!-- Error -->
    </groups>
    <test started-at="2024-06-03T17:30:22 IST" name="Test" finished-at="2024-06-03T17:32:53 IST" duration-ms="150701">
      <class name="SeleniumProj.AutomateFramework2.SubmitOrder">
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:SeleniumProj.AutomateFramework2.SubmitOrder@545b995e]" started-at="2024-06-03T17:31:32 IST" name="initializeDriver" finished-at="2024-06-03T17:31:49 IST" duration-ms="17515" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="submitorder()[pri:1, instance:SeleniumProj.AutomateFramework2.SubmitOrder@545b995e]" started-at="2024-06-03T17:31:49 IST" name="submitorder" finished-at="2024-06-03T17:32:06 IST" duration-ms="16346" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitorder -->
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:SeleniumProj.AutomateFramework2.SubmitOrder@545b995e]" started-at="2024-06-03T17:32:06 IST" name="initializeDriver" finished-at="2024-06-03T17:32:26 IST" duration-ms="20450" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="ErrorValidation()[pri:2, instance:SeleniumProj.AutomateFramework2.SubmitOrder@545b995e]" started-at="2024-06-03T17:32:26 IST" name="ErrorValidation" finished-at="2024-06-03T17:32:52 IST" duration-ms="26058" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login Successfully.] but found [Login Successfully]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login Successfully.] but found [Login Successfully]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at SeleniumProj.AutomateFramework2.SubmitOrder.ErrorValidation(SubmitOrder.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorValidation -->
      </class> <!-- SeleniumProj.AutomateFramework2.SubmitOrder -->
      <class name="SeleniumProj.AutomateFramework2.OrderHistory">
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:SeleniumProj.AutomateFramework2.OrderHistory@10a9d961]" started-at="2024-06-03T17:30:22 IST" name="initializeDriver" finished-at="2024-06-03T17:30:52 IST" duration-ms="29153" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="viewOrders()[pri:1, instance:SeleniumProj.AutomateFramework2.OrderHistory@10a9d961]" started-at="2024-06-03T17:30:52 IST" name="viewOrders" finished-at="2024-06-03T17:31:08 IST" duration-ms="16849" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- viewOrders -->
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:SeleniumProj.AutomateFramework2.OrderHistory@10a9d961]" started-at="2024-06-03T17:31:09 IST" name="initializeDriver" finished-at="2024-06-03T17:31:21 IST" duration-ms="12730" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="ErrorValidation2()[pri:2, instance:SeleniumProj.AutomateFramework2.OrderHistory@10a9d961]" started-at="2024-06-03T17:31:21 IST" name="ErrorValidation2" finished-at="2024-06-03T17:31:31 IST" duration-ms="9667" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login Successfully#] but found [Login Successfully]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login Successfully#] but found [Login Successfully]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at SeleniumProj.AutomateFramework2.OrderHistory.ErrorValidation2(OrderHistory.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorValidation2 -->
      </class> <!-- SeleniumProj.AutomateFramework2.OrderHistory -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
